### PR TITLE
Mavenized project

### PR DESCRIPTION
**Pull request by asm0dey**
Hello!

I've mavenized project, I think it could be added to vaadin addons page in this state.
Also I've removed files, starting with dot for everyone to be able to import project without issues (maven projects are universal),

### CODE REVIEW

**Comment by sockeqwe** [comment]
Hi,
first of all, thank you for your interest in this project and your patch!
Unfortunetly im not a maven fan (indeed 80% of my maven experience was negative) and im not sure if I want to change this project to an maven project. So please give me some time to think about it. But I don't want that all of your work was for nothing.

I tried to apply your patch on my local machine (ubuntu), but unfortunately applying the patch failed with these error messages:
error: patch failed: WebContent/META-INF/MANIFEST.MF:1
error: WebContent/META-INF/MANIFEST.MF: patch does not apply

However github seems to be able to merge this pull request automatically

P.S. Your welcome to work on this project anytime

**Comment by asm0dey** [comment]
Maybe maven fails sometimes with complex project, but I think thisone isn't so complex. Second reason to use maven is to make your add-on available in vaadin repo. And third - make work possible not only in Eclipse, but in any IDE.

About problems with patch: I have no any idea about patching in git - haven't tried it - git is good in merging.
But if you would prefer - I'll refork and change in 1 commit.

P.S. Thank you :)

**Comment by sockeqwe** [comment]
Damn you're right :)
However I would like to merge your patch on my local machine, because as far as I see you use Windows which uses another End Of Line encoding as Linux (and Mac). Git is able to detect and convert this by adding the right parameter. Im not sure how github handle this. So give me some time to figure out how to apply your patch.

**Comment by asm0dey** [comment]
I use Linux:)
Maybe problem is in many commits with strong changes.
Is you wish I can send you all code packed - you'll just need to build it (for test) and change origin from my fork to your.

**Comment by sockeqwe** [comment]
hm ... strange  ... Which one do you use?

**Comment by asm0dey** [comment]
Ubuntu 12.10

**Comment by sockeqwe** [comment]
me too! Alright, so I guess github will do a good job

**Comment by asm0dey** [comment]
Thank from me and other maven-lovers :+1:

**Comment by sockeqwe** [comment]
Just curious: Which IDE do you use in combination with maven? If you use eclipse, which plugin do you use, since m2e seems a little bit bugy to me

**Comment by asm0dey** [comment]
IDEA. New eclipses works perfectly with maven - just do not setup m2e - it's sooo buggy, that I feel myself unable :)
Netbeans works with maven OOTB too. So as eclipses starting from 3.7 or 3.8.

**Comment by asm0dey** [comment]
Oh, I forgot to tell you that I use Eclipse for RCP and RAP developers, but I think other ones have maven integrated too.

**Pull request merged**
